name: Daily Sports Update

on:
  schedule:
    - cron: '0 1 * * *'  # 每天 UTC 01:00 執行（台灣時間 09:00）
  workflow_dispatch:      # 可手動觸發

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Run update script
      run: node scripts/fetch_scores.js

    - name: Commit and push changes
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git fetch origin main
        git checkout -B main origin/main
        git add index.html
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "更新比分 $(date +'%Y-%m-%d')"
          git push origin main --force
        fi
